# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:07:13+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Header, Path

from models import (
    Certs,
    ConsentArtefactResponse,
    ConsentFetchRequest,
    ConsentRequest,
    ConsentRequestInitResponse,
    ConsentRequestStatusRequest,
    ErrorResponse,
    HealthInformationNotification,
    HeartbeatResponse,
    HIPConsentNotification,
    HIPConsentNotificationResponse,
    HIPHealthInformationRequestAcknowledgement,
    HIPHIRequest,
    HIRequest,
    HIUConsentNotificationEvent,
    HIUConsentNotificationResponse,
    HIUConsentRequestStatus,
    HIUHealthInformationRequestResponse,
    HIUSubscriptionNotification,
    HIUSubscriptionNotificationAcknowledgment,
    HIUSubscriptionRequestNotificationAcknowledgement,
    HIUSubscriptionRequestReceipt,
    LinkConfirmationRequest,
    OpenIdConfiguration,
    PatientAuthConfirmRequest,
    PatientAuthConfirmResponse,
    PatientAuthInitRequest,
    PatientAuthInitResponse,
    PatientAuthModeQueryRequest,
    PatientAuthModeQueryResponse,
    PatientAuthNotification,
    PatientAuthNotificationAcknowledgement,
    PatientCareContextLinkRequest,
    PatientCareContextLinkResponse,
    PatientDiscoveryRequest,
    PatientDiscoveryResult,
    PatientIdentificationRequest,
    PatientIdentificationResponse,
    PatientLinkReferenceRequest,
    PatientLinkReferenceResult,
    PatientLinkResult,
    PatientSMSNotifcationRequest,
    PatientSMSNotifcationResponse,
    ServiceProfileResponse,
    SessionRequest,
    SessionResponse,
    ShareProfileRequest,
    ShareProfileResult,
    SubscriptionApprovalNotification,
    SubscriptionRequest1,
)

app = MCPProxy(
    contact={'name': 'National Health Authority', 'url': 'https://ndhm.gov.in/'},
    description='Gateway is the hub that routes/orchestrates the interaction between consent managers and API bridges. There are 5 categories of APIs; discovery, link, consent flow, data flow and  monitoring. To reflect the consumers of APIs, the above apis are also categorized under cm facing, hiu facing and hip facing \n',
    title='Gateway',
    version='0.5',
    servers=[{'description': 'Sandbox', 'url': 'https://dev.ndhm.gov.in/gateway'}],
)


@app.get('/v0.5/.well-known/openid-configuration', tags=['openid_configuration'])
def get_v0_5__well_known_openid_configuration():
    """
    Get openid configuration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/care-contexts/discover',
    description=""" Request for patient care context discover, made by CM for a specific HIP. It is expected that HIP will subsequently return either zero or one patient record with (potentially masked) associated care contexts
  1. **At least one of the verified identifier matches**
  2. **Name (fuzzy), gender matches**
  3. **If YoB was given, age band(+-2) matches**
  4. **If unverified identifiers were given, one of them matches**
  5. **If more than one patient records would be found after aforementioned steps, then patient who matches most verified and unverified identifiers would be returned.**
  6. **If there would be still more than one patients (after ranking) error would be returned**
  7. **Intended HIP should be able to resolve and identify results returned in the subsequent link confirmation request via the specified transactionId**
  8. **Intended HIP should store the discovery results with transactionId and care contexts discovered for subsequent link initiation**
 """,
    tags=['patient_discovery'],
)
def post_v0_5_care_contexts_discover(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: PatientDiscoveryRequest = ...,
):
    """
    Discover patient's accounts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/care-contexts/on-discover',
    description=""" Result of patient care-context discovery request at HIP end. If a matching patient found with zero or more care contexts associated, it is specified as result attribute. If the prior discovery request, resulted in errors then it is specified in the error attribute. Reasons of errors can be 
  1. **more than one definitive match for the given request** 
  2. **no verified identifer was specified**
 """,
    tags=['patient_discovery', 'patient_identification_services'],
)
def post_v0_5_care_contexts_on_discover(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientDiscoveryResult = ...,
):
    """
    Response to patient's account discovery request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v0.5/certs', tags=['openid_configuration'])
def get_v0_5_certs():
    """
    Get certs for JWT verification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consent-requests/init',
    description=""" Creates a consent request to get data about a patient by HIU user. """,
    tags=['consent_request_handling'],
)
def post_v0_5_consent_requests_init(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: ConsentRequest = ...,
):
    """
    Create consent request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consent-requests/on-init',
    description=""" Result of consent request creation for a patient. **consentRequest.id** represents the consentrequest id created by CM. The result must contain either **consentRequest** or the **error** caused. <br/>
  Reasons for error may be
  * Invalid references (e.g patient id, hiu id), purpose, hiTypes, ranges, persmission
 """,
    tags=['consent_request_handling', 'patient_identification_services'],
)
def post_v0_5_consent_requests_on_init(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: ConsentRequestInitResponse = ...,
):
    """
    Response to consent request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consent-requests/on-status',
    description=""" Result of consent request done previously. Status of request can be GRANTED,  DENIED, EXPIRED. If the request was GRANTED, then 
 """,
    tags=['consent_request_handling', 'patient_identification_services'],
)
def post_v0_5_consent_requests_on_status(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: HIUConsentRequestStatus = ...,
):
    """
    Result of consent request status
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consent-requests/status',
    description=""" Get status of consent request done previously """,
    tags=['consent_request_handling'],
)
def post_v0_5_consent_requests_status(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: ConsentRequestStatusRequest = ...,
):
    """
    Get consent request status
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consents/fetch',
    tags=['consent_request_handling', 'patient_identification_services'],
)
def post_v0_5_consents_fetch(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: ConsentFetchRequest = ...,
):
    """
    Get consent artefact
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consents/hip/notify',
    description=""" Notification of consents to health information providers consent request granted, consent revoked, consent expired. Only the GRANTED, REVOKED and EXPIRED status notifications will be sent to HIP.
  1. If consent is granted, status=GRANTED, then consentDetail contains the consent artefact details and signature is available. 
  2. If consent is revoked, then status=REVOKED, and consentId specifes which consent artefact is revoked. 
  3. If the consent has expired, then status=EXPIRED, and consentId specifies which consent artefact has expired. Note, this is also responsibility of the HIP to keep track of consent expiry. Any data request on expired consent artefact must not be done. 
 """,
    tags=['consent_request_handling', 'health_information_requests'],
)
def post_v0_5_consents_hip_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: HIPConsentNotification = ...,
):
    """
    Consent notification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consents/hip/on-notify',
    description=""" This API is called by HIP as acknowledgement to notification of consents, in cases of consent revocation and expiration. 
 """,
    tags=['consent_request_handling', 'health_information_requests'],
)
def post_v0_5_consents_hip_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: HIPConsentNotificationResponse = ...,
):
    """
    Consent notification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consents/hiu/notify',
    description=""" Health information user will get notified about the consent request granted or denied, consent revoked, consent expired. 
1. For consent request grant, status=GRANTED, consentRequestId=<consent-request-id>, and consentArtefacts is an array of generated consent artefact Ids.
2. For consent request expiry, status=EXPIRED, consentRequestId=<consent-request-id>
3. For consent request denied, status=DENIED, consentRequestId=<consent-request-id>
4. For consent revocation, status=REVOKED, consentArtefacts is an array of revoked consent artefact ids
 """,
    tags=['consent_request_handling', 'health_information_requests'],
)
def post_v0_5_consents_hiu_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: HIUConsentNotificationEvent = ...,
):
    """
    Consent notification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consents/hiu/on-notify',
    description=""" This API is called by HIU as acknowledgement to consent notifications, specifically for cases when consent is REVOKED or EXPIRED.
 """,
    tags=['consent_request_handling', 'health_information_requests'],
)
def post_v0_5_consents_hiu_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: HIUConsentNotificationResponse = ...,
):
    """
    Consent notification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/consents/on-fetch',
    description=""" Must contain either consentDetail or error. Possible reason of errors are 
1. consentId passed through /fetch is invalid
 """,
    tags=['consent_request_handling'],
)
def post_v0_5_consents_on_fetch(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: ConsentArtefactResponse = ...,
):
    """
    Result of fetch request for a consent artefact
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/health-information/cm/on-request',
    description=""" Callback API for acknowledgement of Health information request of HIU. CM calls this API when it has validated the Health Information request given the consent id. Either the **hiRequest** or **error** would need to be specified. If the health info request was valid, then the ***hiRequest.transactionId*** specifies the transaction context against which HIP would send over the data.  Possible cases of errors are
  1. **Invalid consent artefact id**
  2. **Consent has expired**
  3. **Date ranges are invalid**
 """,
    tags=['health_information_requests'],
)
def post_v0_5_health_information_cm_on_request(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: HIUHealthInformationRequestResponse = ...,
):
    """
    Health information data request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/health-information/cm/request',
    description=""" Request for Health information against a consent id. CM would generate a transactionId against each consent and pass it as trnasaction context / correlation id to the HIP and also return the same to HIU via /on-request. 
 """,
    tags=['health_information_requests'],
)
def post_v0_5_health_information_cm_request(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: HIRequest = ...,
):
    """
    Health information data request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/health-information/hip/on-request',
    description=""" API called by HIP to acknowledge Health information request receipt. Either the **hiRequest** or **error** must be specified. **hiRequest** element returns the same transactionId as before with a status indicating that the request is acknowledged.  
 """,
    tags=['health_information_requests'],
)
def post_v0_5_health_information_hip_on_request(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: HIPHealthInformationRequestAcknowledgement = ...,
):
    """
    Health information data request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/health-information/hip/request',
    description=""" API called by CM to request Health information from HIP against a validated consent artefact. The transactionId is the correlation id that HIP should use use when pushing data to the **dataPushUrl**. 
 """,
    tags=['health_information_requests'],
)
def post_v0_5_health_information_hip_request(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: HIPHIRequest = ...,
):
    """
    Health information data request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/health-information/notify',
    description=""" API called by HIU and HIP during data-transfer. 
1. HIP on transfer of data would send **sessionStatus** - one of [TRANSFERRED, FAILED]
2. HIP would also send **hiStatus** for each *careContextReference* - on of [DELIVERED, ERRORED]
3. HIU on receipt of data would send **sessionStatus** - one of [TRANSFERRED, FAILED]. For example, FAILED when if data was not sent or if invalid data was sent
4. HIU would also send **hiStatus** for each *careContextReference* - one of [OK, ERRORED] 
 """,
    tags=[
        'health_information_requests',
        'patient_profile_notifications',
        'subscription_management_services',
    ],
)
def post_v0_5_health_information_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: HealthInformationNotification = ...,
):
    """
    Notifications corresponding to events during data flow
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/v0.5/heartbeat', tags=['consent_request_handling'])
def get_v0_5_heartbeat():
    """
    Get consent request status
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/v0.5/hi-services/{service-id}',
    description=""" This API is meant for displaying the bridge service details by the serviceId provided .
 """,
    tags=['patient_identification_services'],
)
def get_v0_5_hi_services__service_id(
    authorization: str = Header(..., alias='Authorization'),
    service_id: str = Path(..., alias='service-id'),
):
    """
    Get bridge service details/profile by the serviceId provided.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/add-contexts',
    description=""" API to submit care-context to CM for HIP initiated linking. The API must accompany the "accessToken" fetched in the users/auth process.  
  1. subsequent usage for accessToken may be invalid if it was meant for one-time usage or if it expired
 """,
    tags=['care_context_linking'],
)
def post_v0_5_links_link_add_contexts(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientCareContextLinkRequest = ...,
):
    """
    API for HIP initiated care-context linking for patient
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/confirm',
    description=""" API to submit the token that was sent by HIP during the link request. 
 """,
    tags=['consent_request_handling', 'care_context_linking'],
)
def post_v0_5_links_link_confirm(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: LinkConfirmationRequest = ...,
):
    """
    Token submission by Consent Manager for link confirmation
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/init',
    description=""" Request from CM to links care contexts associated with only one patient
  1. **Validate account reference number and care context reference number**
  2. **Validate transactionId in the request with discovery request entry to check whether there was a discovery
      and were these care contexts discovered or not for a given patient**
  3. **Before eventual link confirmation, HIP needs to authenticate the request with the patient(eg: OTP verification)**
  4. **HIP should communicate the mode of authentication of a successful request to Consent Manager**
 """,
    tags=['care_context_linking', 'patient_discovery'],
)
def post_v0_5_links_link_init(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: PatientLinkReferenceRequest = ...,
):
    """
    Link patient's care contexts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/on-add-contexts',
    description=""" If the accessToken is valid for purpose of linking, and specified details provided, CM will send "acknoweldgement.status" as SUCCESS. If any error occcurred, for example invalid token, or other required patient or care-context information not provided, then "error" attribute conveys so. 
  1. **accessToken must be valid and must be for the purpose of linking**
 """,
    tags=['care_context_linking', 'patient_discovery'],
)
def post_v0_5_links_link_on_add_contexts(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: PatientCareContextLinkResponse = ...,
):
    """
    callback API for HIP initiated patient linking /link/add-context
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/on-confirm',
    description=""" Returns a list of linked care contexts with patient reference number.
  1. **Validated and linked account reference number**
  2. **Validated that the token sent from Consent Manager is same as the one generated by HIP**
  3. **Verified that same Consent Manager which made the link request is sending the token**
  4. **Results of unmasked linked care contexts with patient reference number**
 """,
    tags=['care_context_linking', 'patient_discovery'],
)
def post_v0_5_links_link_on_confirm(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientLinkResult = ...,
):
    """
    Token authenticated by HIP, indicating completion of linkage of care-contexts
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/links/link/on-init',
    description=""" Result of patient care-context link request from HIP end. This happens in context of previous discovery of patient found at HIP end, therefore the link requests ought to be in reference to the patient reference and care-context references previously returned by the HIP. The correlation of discovery and link request is maintained through the transactionId. HIP should have
  1. **Validated transactionId in the request to check whether there was a discovery done previously, and the link request corresponds to returned patient care care context references**
  2. **Before returning the response, HIP should have sent an authentication request to the patient(eg: OTP verification)**
  3. **HIP should communicate the mode of authentication of a successful request**
  4. **HIP subsequently should expect the token passed via /link/confirm against the link.referenceNumber passed in this call**




















  
The error section in the body, represents the potential errors that may have occurred. Possible reasons:
  1. **Patient reference number is invalid**
  2. **Care context reference numbers are invalid**
 """,
    tags=['care_context_linking', 'patient_discovery'],
)
def post_v0_5_links_link_on_init(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientLinkReferenceResult = ...,
):
    """
    Response to patient's care context link request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/patients/find',
    description=""" This API is meant for identify to patient given her consent-manager-user-id
 """,
    tags=['patient_identification_services', 'patient_discovery'],
)
def post_v0_5_patients_find(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientIdentificationRequest = ...,
):
    """
    Identify a patient by her consent-manager user-id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/patients/on-find',
    description=""" If a patient is found then patient.name contains the patients name. 
Otherwise, patient is not provided, and possibly error is raised for invalid requests
Note in addition to the "Authorization" header, one of the following headers must be specified
1. specify **X-HIU-ID** if the requester is HIU (identified from /find requester.id)
2. specify **X-HIP-ID** if the requester is HIP (identified from /find requester.id)
 """,
    tags=['patient_identification_services', 'consent_request_handling'],
)
def post_v0_5_patients_on_find(
    authorization: str = Header(..., alias='Authorization'),
    body: PatientIdentificationResponse = ...,
):
    """
    Identification result for a consent-manager user-id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/patients/profile/on-share',
    description=""" Result of patient share profile request at HIP end.
 """,
    tags=['patient_profile_notifications', 'patient_identification_services'],
)
def post_v0_5_patients_profile_on_share(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: ShareProfileResult = ...,
):
    """
    Response to patient's share profile request
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/patients/profile/share',
    description=""" Request for sharing patient's profile details to HIP
 """,
    tags=['patient_profile_notifications', 'patient_discovery'],
)
def post_v0_5_patients_profile_share(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: ShareProfileRequest = ...,
):
    """
    Share patient profile details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/patients/sms/notify',
    description=""" API to send SMS notifications to patient with custom deeplink.
 """,
    tags=['patient_profile_notifications', 'health_information_requests'],
)
def post_v0_5_patients_sms_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientSMSNotifcationRequest = ...,
):
    """
    API for HIP to send SMS notifications to patients
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/patients/sms/on-notify',
    description=""" If the SMS notification is successfully sent to patient then "status" will be "ACKNOWLEDGED" with no error.
If the SMS notification is failed then "status" will be "ERRORED" with error.
 """,
    tags=['patient_profile_notifications', 'subscription_management_services'],
)
def post_v0_5_patients_sms_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    body: PatientSMSNotifcationResponse = ...,
):
    """
    Acknowledgment response for SMS notification sent to patient by HIP
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/v0.5/sessions', tags=['user_authentication_services'])
def post_v0_5_sessions(body: SessionRequest):
    """
    Get access token
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/subscription-requests/cm/init',
    description=""" creates a request for subscription. The subscription categories can be for care-contexts linkages or availability of data against existing care-contexts. Note that the requester must have HIU role """,
    tags=['subscription_management_services'],
)
def post_v0_5_subscription_requests_cm_init(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: SubscriptionRequest1 = ...,
):
    """
    Request for subscription
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/subscription-requests/cm/on-init',
    description=""" This callback API acknowledges the request for subscription from a HIU, and sends back a "id" that will be used when the patient/user approves or denies the subscription. 
 """,
    tags=['subscription_management_services', 'health_information_requests'],
)
def post_v0_5_subscription_requests_cm_on_init(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: HIUSubscriptionRequestReceipt = ...,
):
    """
    callback API for the /subscription-requests/cm/init to notify a HIU on acceptance/acknowledgement of the request for subscription.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/subscription-requests/hiu/notify',
    description=""" This API is used by CM to notify a HIU to grant or deny a request for subscription, and also to notify that in case an existing subscription is revoked or expired. For notifying that a particular subscription request was GRANTED or DENIED, the **subscriptionRequestId** is passed. 
 """,
    tags=['subscription_management_services', 'health_information_requests'],
)
def post_v0_5_subscription_requests_hiu_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: SubscriptionApprovalNotification = ...,
):
    """
    Notification for subscription grant/deny/revoke
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/subscription-requests/hiu/on-notify',
    description=""" This API is called by HIU as acknowledgement to subscription request relevant notifications. 
 """,
    tags=['subscription_management_services'],
)
def post_v0_5_subscription_requests_hiu_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: HIUSubscriptionRequestNotificationAcknowledgement = ...,
):
    """
    Callback API for /subscription-requests/hiu/notify to acknowledge receipt of notification.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/subscriptions/hiu/notify',
    description=""" This API is used by CM to notify a HIU for notification relevant to subscription. Notifications are sent to subscribed HIUs whenever a new care-context is linked or new data is available on an existing linked care-context. 
1. if event.category = LINK, then only care-contexts are passed when new care-contexts are linked for patient. 
2. If event.category = DATA, then hiTypes are passed. Care-context is passed only if the subscribed HIU has any valid consent for that care-context
 """,
    tags=['subscription_management_services', 'health_information_requests'],
)
def post_v0_5_subscriptions_hiu_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: HIUSubscriptionNotification = ...,
):
    """
    Notification to HIU on basis of a granted subscription
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/subscriptions/hiu/on-notify',
    description=""" This API is called by HIU as acknowledgement to consent notifications, specifically for cases when consent is REVOKED or EXPIRED.
 """,
    tags=['subscription_management_services'],
)
def post_v0_5_subscriptions_hiu_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: HIUSubscriptionNotificationAcknowledgment = ...,
):
    """
    Callback API for /subscriptions/hiu/notify to acknowledge receipt of notification.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/confirm',
    description=""" This API is called by HIP/HIUs to confirm authentication of users. The transactionId returned by the previous callback API /users/auth/on-init must be sent. If Authentication is successful the callback API will send an "access token" for subsequent purpose specific API calls. Note only **credential.authCode** or **credential.demographic** should be sent
  1. demographic details are only required for  demographic auth as of now. 
  2. demographic details are required only in MEDIATED cases and if the **auth.mode** so demands. e.g. if **auth.mode** is DEMOGRAPHICS. Usually for demographic authentication, the name, gender and DOB must be exactly as specified in User Account.
  3. demographic.identifier is optional, however maybe required if authentication so mandates. 
  4. credential.authCode is required for other MEDIATED authentication like MOBILE_OTP, AADHAAR_OTP. 
 """,
    tags=['user_authentication_services', 'consent_request_handling'],
)
def post_v0_5_users_auth_confirm(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientAuthConfirmRequest = ...,
):
    """
    Confirmation request sending token, otp or other authentication details from HIP/HIU for confirmation
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/fetch-modes',
    description=""" This API is meant for identify supported authentication modes for a patient given a specific purpose
 """,
    tags=['user_authentication_services', 'patient_identification_services'],
)
def post_v0_5_users_auth_fetch_modes(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientAuthModeQueryRequest = ...,
):
    """
    Get a patient's authentication modes relevant to specified purpose
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/init',
    description=""" This API is called by HIPs to initiate authentication of users. A transactionId is retuned by the corresponding callback API for confirmation of user auth.
 """,
    tags=['user_authentication_services', 'patient_identification_services'],
)
def post_v0_5_users_auth_init(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientAuthInitRequest = ...,
):
    """
    Initialize authentication from HIP
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/notify',
    description=""" This API is called by CM to confirm authentication of users. The transactionId returned is same as that passed in /auth/on-init. The "auth.status" conveys whether the request was GRANTED or DENIED.

  1. **auth.accessToken** - is specific to the purpose mentioned in the /auth/init. This token needs to be used for initiating the intended action. For example for HIP initiated linking of care-contexts
  2. **NOTE**, only one of **X-HIP-ID** or **X-HIU-ID** will be sent as part of header, not both.
  3. The payload is conditional to the purpose of auth. If purpose specified in /auth/init is KYC or KYC_AND_LINK, then patient details are passed. **auth.accessToken** is passed only if the purpose is LINK or KYC_AND_LINK.
 """,
    tags=['user_authentication_services', 'patient_identification_services'],
)
def post_v0_5_users_auth_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: PatientAuthNotification = ...,
):
    """
    notification API in case of DIRECT mode of authentication by the CM
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/on-confirm',
    description=""" This API is called by CM to confirm authentication of users.

  1. **auth.accessToken** - is specific to the purpose mentioned in the /auth/init. This token needs to be used for initiating the intended action. For example for HIP initiated linking of care-contexts
  2. **NOTE**, only one of **X-HIP-ID** or **X-HIU-ID** will be sent as part of header, not both.     
 """,
    tags=['user_authentication_services'],
)
def post_v0_5_users_auth_on_confirm(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: PatientAuthConfirmResponse = ...,
):
    """
    callback API for /auth/confirm (in case of MEDIATED auth) to confirm user authentication or not
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/on-fetch-modes',
    description=""" If a patient is found then **auth** attribute contains the supported modes for the specified purpose. 
Otherwise, error is raised for invalid requests or for non-existent id.
Note in addition to the "Authorization" header, one of the following headers must be specified
1. **X-HIU-ID** if the requester is HIU (identified from /auth/fetch-modes requester.id)
2. **X-HIP-ID** if the requester is HIP (identified from /auth/fetch-modes requester.id)
 """,
    tags=['patient_identification_services', 'consent_request_handling'],
)
def post_v0_5_users_auth_on_fetch_modes(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: PatientAuthModeQueryResponse = ...,
):
    """
    Identification result for a consent-manager user-id
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/on-init',
    description=""" If the patient's id is valid, CM will return a transactionId as initialization of user auth. If the request is valid, then 'auth.mode' will convey how the authentication should be done. The authentication can be *mediated* or *direct*. For mediated authentication modes, HIP or HIU is epected to send over relevant code (OTP/token) or demographic info via subsequent API call to /auth/confirm. for direct authentication case, CM will notify requester through/users/auth/notify API. 

  1. **auth.mode** conveys whats the mode of authentication is, and what is expected from HIP/HIU in the subsequent /auth/confirm API call. Possible values 
      1. MOBILE_OTP - auth via OTP to registered mobile. Mediated. 
      2. AADHAAR_OTP - auth initiated with Aadhaar with OTP. Mediated. 
      3. DEMOGRAPHICS - auth initiated with demographic verification
      4. DIRECT - for authentication directly with the patient. e.g. Mobile App, SMS. In this case, the HIP/HIU is not expected to call subsequent /auth/confirm call. CM will do direct authentication with the User (e.g. Mobile App, SMS etc) and will notify requester
  2. **meta.expiry** conveys the expiry time of the token and the authentication session
  3. **NOTE**, only one of **X-HIP-ID** or **X-HIU-ID** will be sent as part of header, not both. 




















  
The error section in the body, represents the potential errors that may have occurred. Possible reasons:
  1. Patient id is invalid
 """,
    tags=['user_authentication_services', 'patient_identification_services'],
)
def post_v0_5_users_auth_on_init(
    authorization: str = Header(..., alias='Authorization'),
    x__h_i_p__i_d: str = Header(..., alias='X-HIP-ID'),
    x__h_i_u__i_d: str = Header(..., alias='X-HIU-ID'),
    body: PatientAuthInitResponse = ...,
):
    """
    Response to user authentication initialization from HIP
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/v0.5/users/auth/on-notify',
    description=""" This API is called by HIU/HIPs to confirm acknowledgement for receipt of auth notification is case of DIRECT authentication. 
 """,
    tags=[
        'health_information_requests',
        'subscription_management_services',
        'user_authentication_services',
    ],
)
def post_v0_5_users_auth_on_notify(
    authorization: str = Header(..., alias='Authorization'),
    x__c_m__i_d: str = Header(..., alias='X-CM-ID'),
    body: PatientAuthNotificationAcknowledgement = ...,
):
    """
    callback API by HIU/HIPs as acknowledgement of auth notification
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
